### ISSUE TITLE
How are /users/addresses used?

### ISSUE THREAD

**Issue by mitraman** [Haufe-Lexware/api-user-management#3]
This API allows me to create new address resources for a single user.  But, I'm not clear on how these might be used by the app developer.  Does the app need to keep track of what each of these addresses mean or is an ordered list appropriate?  Is it common for end-users to have multiple addresses with no metadata about what the addresses are used for?

**Comment by toraonaca** [comment]
The user usually has one private address (which is not really used in any process at the moment). Not sure if in the future there will be a need for multiple addresses and address types.
Usually in order to place an order, a user needs to have a company attached, which, in turn, has its own billing and delivery address. In case he does not, but still orders, the private address can be used as billing/delivery.

**Comment by marc00s** [comment]
Why do we have that requirement for a user having a company attached? Wouldn't it make sense me as a private person placing an order? I would then expect to have two possible address types, billing and shipping. If we add an address type field in the address ressource, wouldn't it make it clearer?

**Comment by toraonaca** [comment]
Because all orders go through to SAP which does the billing. We are just acting as a proxy. And SAP needs debtor/company information, as users (contact persons) cannot exist but in the context of a company. This is why we need the connection with the company.

**Comment by toraonaca** [comment]
The final solution is to have a type in the address, which now is shipping/billing, and just one address of each type for a company. New types can be added, need be.
