### ISSUE TITLE
POST /users/{id}/state should be PUT

### ISSUE THREAD

**Issue by mitraman** [Haufe-Lexware/api-user-management#4]
Changing the user state looks like an idempotent call and feels like an udpate in the CRUD model.  This should be PUT /users/{id}/state.

**Comment by toraonaca** [comment]
I have a problem with what my understanding of PUT is (maybe wrong): a PUT is one on one with a GET. When you act on the /state you basically do an update of state, but the request itself contains information needed for the transition to the new state. For instance, if the current state is PENDING (not yet activated), the request for transitioning to active will contain an activation code, needed to make the transition. That's why I thought POST was suitable, as it's more like an action resource.

**Comment by mitraman** [comment]
ok, you were using POST in the 'do some work' sense, not in the POST==CREATE sense.  I understand now.

You may want to change the name of this resource to make this distinction clearer.  e.g. POST /users/{id}/changeState or POST /users/id/stateChangeProcessor tells me right away I'm not applying the CRUD pattern.

**Comment by toraonaca** [comment]
OK, I will do that.
