### ISSUE TITLE
POST /users/reset_password badly named?

### ISSUE THREAD

**Issue by mitraman** [Haufe-Lexware/api-user-management#6]
related to issue #5 
I would expect a call to POST /users/reset_password to reset a password.. instead this endpoint appears to have a change password function.

There is also a POST /users/change_password.  This whole section is confusing and needs to be re-designed.

**Comment by toraonaca** [comment]
This is the functionality: in order to reset a password to something else, you need to have a reset code. So it's a two step process: get a reset code and then reset the password in another request using the reset code. Part of getting the reset code might actually be the sending out of the email (with a link in it - containing the reset code - that gets you to a page that validates the code and allows you to set your new password).

So, this could be replaced with:
POST on /reset_password
POST on /change_password (with an additional reset_code in the request)

**Comment by mitraman** [comment]
I'm still a bit confused.  Can you describe the interaction again in terms of the client application, end-user and server?

**Comment by toraonaca** [comment]
In order to reset someone's password, a client application must send a request containing the email of the user (username), the new password and the reset code (so that not anyone can reset some one else's password) to us. In order to get the reset code, the client application must call us to get the code. Some client applications request the reset code but also want the user to receive an email with a link that contains the code and if the user clicks the link in the email will get to a page where the code is validated and he can enter the new password. Of course, in this case, the client application receiving the reset code won't do anything with it (since the end user already received the email...). They use the endpoint to just trigger the sending of the email (and the creation of the reset code).

Part two is the request to change the password (providing the reset code instead of the old password).

**Comment by toraonaca** [comment]
So, at this point, I am thinking that maybe this line of operations would work better:
POST on /reset_password to get a reset code and send out the email (if needed) -basically trigger the reset of the password
POST on /change_password to actually change the password (in this case, the change_password resource would receive either the reset_code or the old password, depending on the workflow - step 2 of resetting the password or plain change password when the user knows his old password)

**Comment by toraonaca** [comment]
After checking with the exising clients of the old API, this is the final design:
POST on /reset_password to send an email containing a link where the user can access a page where he can enter his new password.
POST on /change_password for changing the password of a user who knows his current password.
