### ISSUE TITLE
Company addresses are generically typed, but the API is type specific

### ISSUE THREAD

**Issue by mitraman** [Haufe-Lexware/api-user-management#9]
It appears that I can create a company address with any type string that I want.  But, the API also allows me to retrieve a billing address (/company/{id}/addresses/billing) directly.  This feels like a conceptual mis-match.

**Comment by toraonaca** [comment]
There are two types of addresses a company can have: billing and shipping. We may add some in the future.  I should change the sub-resource for addresses to /addresses/{type}.

**Comment by mitraman** [comment]
You will need to make a design decision here.  How likely are you to add new addresses in the future?  How many new address types have been added over the last five years?

There is a universal principle of design called the flexibility-usability tradeoff.  You are going to have to decide how much usability you want to trade for this increase in 'address type' flexibility.  

I suspect you can get away with having named properties forr billing and shipping addresses, but you'll need to do some research to make that decision.

**Comment by raulfiru** [comment]
In the case of address types. We have multiple types but they remain quite stable. There are all related to different backed processes. Shipping, billing.

There is another type used for marketing purposes but this channel is less and less used. 

Point being. i don't expect changes in address types.

**Comment by hlgr360** [comment]
Why can't we have dedicated endpoints: shipping-address and billing-address. they are distinct .. and they might even be distinct in ordinality. in amazon for instance I have exactly one billing address per payment method, but any number of shipping addresses.
In general I find having dedicated endpoints works better instead of type property. By looking at the url I know exactly what kind of type of address I am interacting with. And I can evolve it independently instead of having one pile of addresses all trying to be everything to everyone.
Just a idea.

**Comment by raulfiru** [comment]
i would also separate them semantically. for both put and get. if we will have another type of address in the future we can add it.

In that case, do we still need type?

**Comment by marc00s** [comment]
I hear what you're saying, and billing and shipping are the two that are
always there. But by separating them, wouldn't that make it harder to use
them? There are cases where you want to set the address - both the same -
in one go, the same as reading them, or don't you think?

Am Montag, 22. Juni 2015 schrieb raulfiru :

**Comment by raulfiru** [comment]
it would be the same as today...because one address can have 1 type.
